export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCES = 'ADD_PRODUCT_SUCCES'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCST_DOWNLOAD_SUCCESS';  
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const PRODUCT_DELETED_SUCCESS = 'PRODUCT_DELETED_SUCCESS'
export const PRODUCT_DELETED_ERROR = 'PRODUCT_DELETED_ERROR'

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const START_EDIT_PRODUCT ='START_EDIT_PRODUCT'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_ERROR = 'PRODUCTEDITD_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT ='HIDE_ALERT'