export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCES = 'ADD_PRODUCT_SUCCES'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCST_DOWNLOAD_SUCCESS';  
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR';
